name: job_match
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/custom_icons/
    - assets/images/job_match.jpg
    - assets/images/profile_background.jpeg
    # - assets/images/up_logo.png # Ejemplo si añades nuevos logos
    # - assets/images/dribbble_logo.png # Ejemplo
    # - assets/images/apple_logo.png # Ejemplo
    # - assets/images/microsoft_logo.png # Ejemplo

